### ISSUE TITLE
Short/long disortion on left channel

### ISSUE THREAD

**Issue by jthecodebuilder** [gtaylormb/opl3_fpga#12]
This might because this is a bug in opl3_fpga-apps or I'm using an older version, but on certain music, the left audio disorts a bit or a lot (especially when there's more than two sound channels being played in MONOTONE).

**Comment by gtaylormb** [comment]
This might be due to the levels being too high. I've experienced the same thing on my zybo and had to lower them. You can decrease the volume by modifying the i2c init commands to the dac. The DAC might be shitty, not sure.

I bought another pmod DAC and I just need to get around to testing if that has the same issues.

Greg

⁣Sent from Blue ​

**Comment by gtaylormb** [comment]
For one thing, the output digilent chose to use on the DAC is the amplified headphone output. Wished they chose the line out.

Greg

⁣Sent from Blue ​

**Comment by gtaylormb** [comment]
Have not seen this in all recent builds, closing.
