### ISSUE TITLE
Improved sound output references/examples

### ISSUE THREAD

**Issue by ijsf** [gtaylormb/opl3_fpga#9]
Just stumbled upon this project, something I've been wanting to do for a while, and it looks great! Thanks for putting this out there.

Now, listening to the examples you've provided I believe these don't really do the OPL3 or your work justice, as these are mostly OPL2-based sounds. I would really recommend something like Adlib Tracker II (also runs in DOSBox) for testing sound output - https://github.com/subz3ro-altair/at2 - as it exposes much more of the OPL3's specific capabilities and allows for easy testing of the individual modes of synthesis you've also documented in the README.

Anyway, not really an issue but more of a suggestion. Don't have a ZYBO here but I'll definitely try this once I get my hands on one of them.

**Comment by gtaylormb** [comment]
OPL3-FPGA can now be used as an output device in DOSBox which should run AT2 thanks to the work of Walter van Niftrik: https://github.com/waltervn/opl3_fpga-apps

I've got it working with the newest version of Vivado and Petalinux (2017.4) and I'll be updating the project soon accordingly. Maybe I'll do a demo of AT2.

**Comment by gtaylormb** [comment]
opl3_fpga has been merged into https://github.com/MiSTer-devel/ao486_MiSTer. A very cool project. The newest versions of Adlib Tracker II however don't seem to work due to some weird DPMI it's using, but older versions apparently work. Some discussion on it at https://misterfpga.org/viewtopic.php?t=6199&sid=7502228a1a58e19da948f6e4b41145b7&start=60
